research_task:
  description: >
    Você é um agente pesquisador. Sua única fonte de informação é a ferramenta 'Wikipedia API'. 
    Pesquise **apenas** sobre o tópico '{topic}' fornecido e nunca use outras fontes.
    Produza um relatório detalhado, completo e preciso, evitando informações inventadas.

    **Instruções importantes:**
    - Estruture o relatório obrigatoriamente nas seguintes seções:
      1. **Visão Geral:** resumo conciso do tópico.
      2. **Contexto Histórico:** origem e marcos principais do tópico.
      3. **Fatos Principais/Dados:** inclua pelo menos 3 a 5 fatos ou estatísticas verificáveis.
      4. **Terminologia e Conceitos:** defina termos importantes relacionados ao tópico.
      5. **Relevância/Impacto:** explique por que o tópico é importante atualmente.

    - Seja claro, objetivo e factual.
    - Não crie opiniões nem adicione informações não confirmadas.
    - Formate o resultado em **Markdown**, mantendo títulos e seções claramente definidos.

  expected_output: >
    Um relatório em Markdown com todas as seções solicitadas, claro, conciso e fiel às informações da Wikipedia. 
    Este relatório deve servir como base factual completa para um redator produzir um artigo sobre o tópico '{topic}'.

  agent: researcher

fact_check_task:
  description: >
    Você é um agente verificador de fatos. Sua função é analisar o relatório produzido pelo agente pesquisador e 
    confirmar se todas as informações apresentadas estão coerentes, completas e bem estruturadas.  
    Certifique-se de que não há contradições, repetições ou informações inventadas.

    Analise o relatório **sem consultar a Wikipedia mais de uma vez**. 
    Caso precise confirmar informações, faça uma única verificação geral e utilize apenas trechos realmente relevantes da Wikipedia.  
    Evite requisições múltiplas à ferramenta 'WikipediaTool'.

    **Instruções importantes:**
    - Analise cada seção do relatório (Visão Geral, Contexto Histórico, Fatos, Conceitos e Impacto).
    - Identifique possíveis inconsistências, omissões ou erros de interpretação.
    - Garanta que o texto é fiel às informações encontradas na Wikipedia.
    - Verifique se os fatos e números estão dentro de um contexto lógico e cronológico.
    - Se houver algo incorreto, aponte de forma clara e objetiva.
    - **Finalize sua resposta com um relatório completo em Markdown, sem tentar usar ferramentas novamente.**
    - **Não adicione pensamentos, apenas o relatório final formatado.**

  expected_output: >
    Um relatório resumido em Markdown listando:
    - Os pontos verificados como corretos.
    - As inconsistências ou contradições detectadas (se houver).
    - Sugestões de ajustes para melhorar a precisão e a clareza do conteúdo.  
    O tom deve ser neutro, técnico e objetivo, sem alterar o conteúdo original.
    A resposta deve ser o relatório final, não instruções de execução ou raciocínio.

  agent: fact_checker

writing_task:
  description: >
    Reescrever o relatório técnico validado pelo agente de verificação de fatos
    em um artigo envolvente, claro e bem estruturado.  
    Basear-se **exclusivamente** nas informações verificadas, sem adicionar novos dados.  
    O artigo deve conter:
      - Um título principal;
      - Um resumo introdutório (mínimo 50 e máximo 500 caracteres);
      - Um corpo dividido em seções, cada uma com título e conteúdo;
      - Um total mínimo de 300 palavras;
      - Fontes de referência listadas ao final.  
    O artigo deve ser formatado em **Markdown** e pronto para publicação.
  expected_output: >
    Um artigo completo, coeso e informativo, contendo os campos necessários
    para gerar automaticamente um objeto ArticleOut válido.
  agent: writer
  context:
    - fact_check_task
